file(GLOB_RECURSE TEST_SOURCES "*.cc" "*.cpp")

foreach(TEST_FILE ${TEST_SOURCES})
  get_filename_component(TEST_NAME ${TEST_FILE} NAME_WE)

  add_executable(${TEST_NAME} ${TEST_FILE})
  target_link_libraries(${TEST_NAME} PRIVATE powerlawann GTest::gtest_main)

  set_target_properties(${TEST_NAME} PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/test
  )

  add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})

  message(STATUS "Target test: ${TEST_NAME} (${TEST_FILE})")
endforeach()
